name: Build and Push

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - sync

jobs:
  build:
    uses: poketwo/workflows/.github/workflows/docker-image.yaml@main
    with:
      package-name: gateway-proxy
    secrets:
      GIT_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
